# Engagement with hybrid workers {.unnumbered}

This is template for creating a scenario. To create a new scenario, copy this file to a new file in this same directory 'scenarios/' then fill in your own content in the different sections.

## Overcoming barriers to engagement in a hybrid team

### Scenario parameters

These are considerations that the facilitator / implementor needs to understand when posing a scenario.

* How many people are already in the (established) team?
* What is the team composition? (e.g. location, personalities)
* What are the hybrid working patterns of the team members? (E.g. which people mainly work from home or a centralised office? Do people have different individual hybrid working patterns?)
* What are the career levels of team members and associated technical experience? 
* Does the organisation have policy or guidance on hybrid working?
* Is the person a permanent or temporary addition to the team?
* How does the team maintain contact with each other (e.g. which technology is used, can people have private conversations remotely)? 
* Are there barriers to communication (e.g. language, technology, cultural)?
* Does the organisation provide flexible working arrangements (i.e. family committments, religious observance, caring responsibilities)?
* Are there accessibility requirements to consider? 
* Are there mental health requirements to consider (e.g anxiety about returning to the office, other non-work related problems)?
* What are the workloads of your team members? 

### Skill
What skill are you practicing?
- Difficult conversations / communication
- Conflict management
- Finding / using / signposting to organisational resources
- Decision making / implementing/communicating decisions
- Building an inclusive team and culture

### Mini-scenarios
Situations when the problem is approached / "scenes" in the story
1. Define what engagement levels you would like in your team. Communicate that to an hybrid team.
    - are you aware of your duty of care as a leader?
    - are you awaree of organisational policies / contract types etc?
2. How do you assess if people are accepting/respecting your expectations? When did you realise that the engagement was lacking?
    - A member of the team has repetedly missed team meetings (related to the problem of how do you measure engagement)
    - Are tasks equally distributed?
3. How do you initiate a conversation when something is raised?
    - Who has raised a concern? (individual, team member, you, your management) 
4. How might you follow up on the initial conversation?


### Format
Is this an individual, paired or group exercise?

### Directions
Are there any particular directions for this exercise?


### Time
How much time should participants spend on this exercise? How much on the scenario and how much on the reflection questions?  

### Things to remember
Are there quick tip things to remember from the lesson in this scenario?

### Scenario
Write the story of the scenario. It may just be for one person, or you may write 'parts' for 2 or more people. 

Person 1: 

Person 2:


### Reflection questions

What questions might you ask yourself or others after the scenario?

* How do you create a culture where people can come to you and share problems? 
