# Example Scenario {.unnumbered}

This is an example scenario. To create a new scenario, copy this file to a new file in this same directory 'scenarios/' then fill in your own content in the different sections.


## Feedback: Scenario 1

### Skill
The skill being practiced is giving feedback. 

### Format
2 person

### Directions
In this scenario one person will be the one giving the feedback and the other will be the one receiving the feedback. Both people should read the scenario.

### Time
Spend 3 minutes giving the feedback and responding, 2 minutes discussing.

### Things to remember
Remember: You want to provide feedback, so that the student is aware of the issues and can work with you on finding solutions. You don't want to provide solutions for the student. 

### Scenario parameters
These are considerations that the facilitator / implementor needs to understand when posing a scenario.

- How many people are already in the (established) team?
- What is the team composition? (e.g. location, personalities)
- What are the hybrid working patterns of the team members? (E.g. which people mainly work from home or a centralised office? Do people have different individual hybrid working patterns?)
- What are the career levels of team members and associated technical experience? 
- Does the organisation have policy or guidance on hybrid working?
- Is the person a permanent or temporary addition to the team?
- How does the team maintain contact with each other (e.g. which technology is used, can people have private conversations remotely)? 
- Are there barriers to communication (e.g. language, technology, cultural)?
- Does the organisation provide flexible working arrangements (i.e. family committments, religious observance, caring responsibilities)?
- Are there accessibility requirements to consider? 
- Are there mental health requirements to consider (e.g anxiety about returning to the office, other non-work related problems)?
- What are the workloads of your team members? 

### Scenario
Person 1: You are a professor leading a lab of 3 students and 2 postdocs. A third year student in the lab has been been working on a project for awhile and not making progress. The student is frustrated with their lack of progress, and you have to report out on the findings from this grant in 6 months in order to continue receiving funding. In your regular meetings with your student you notice that they keep using the same approaches and seem reluctant to try new approaches. 

Person 2: You are a third year graduate student. You've been working on a project for awhile and are frustrated you're not making progress. You are embarrassed though that you haven't made more progress and don't want to look bad to your professor or lab mates, but don't know what to do to change things. 


### Reflection questions
Person 2: How did that feedback feel to you?   