project:
  type: website
  output-dir: docs

book:
  title: "Inclusive Research Leadership"
  author: "Neil Chue Hong, Tracy Teal"
  date: "4/2/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: scenarios.qmd
      chapters:
        - scenarios/scenario_template.qmd
        - scenarios/scenario_example.qmd
        - scenarios/scenario_engagement.qmd
    - part: references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



