# Preface {.unnumbered}

These are materials that could be used in an inclusive research leadership workshop. These are currently under development in this repository <https://github.com/tracykteal/inclusive-research-leadership>.

This content is written in Quarto. To learn more about Quarto books visit <https://quarto.org/docs/books>.

### About this content

Researchers and research software developers have developed experience and expertise in their areas of work. They have spent time learning how to code, analyze data and are experts in their domains. As people become leaders in their field, whether it’s a small group or a large team, they also need to develop leadership and management skills, but often haven’t had the opportunity to learn them, or are self-taught. This lack of knowledge around team leadership negatively impacts the person in the leadership position as well as those in their team. Therefore there is the opportunity for short-format, practical, hands-on training for people in or transitioning to research leadership roles.

We know a lot now from research around leadership as to what makes effective leadership, meaning leadership that allows a team to do its best work, both for the individuals on the team, and the team itself. That includes elements of creating psychological safety and providing opportunities for mastery, autonomy and purpose, and centering inclusiveness, accessibility and culturally responsive practices. Overall, what we know makes for effective leadership, is not always how we see leadership practiced. Therefore not only are there not learning opportunities, but what people learn by ‘watching’ are not effective practices. 

We are developing a course on Inclusive Research Leadership modeled on the The Carpentries 2-day workshop format, which aims to provide participants with opportunities to learn about leadership, based on what we know works, and that values people - both the leader themselves and the people they lead. 

